version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "swift"
    directory: "packages/react-native-v2"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "packages/react-native-v2/android"
    schedule:
      interval: "weekly"