packages:
  - actions/*
  - packages/*
  - examples/*
  - e2e-tests/**
catalog:
  "@actions/core": ^1.11.1
  "@actions/github": ^6.0.0
  "@aws-sdk/client-s3": ^3.420.0
  "@babel/core": ^7.20.0
  "@changesets/cli": ^2.27.10
  "@eslint/js": ^9.12.0
  "@inquirer/prompts": ^3.3.2
  "@peculiar/webcrypto": ^1.5.0
  "@playwright/test": ^1.49.1
  "@swc/core": ^1.4.11
  "@types/applepayjs": ^14.0.8
  "@types/googlepay": ^0.7.6
  "@types/jest": ^28.1.2
  "@types/jsdom": ^21.1.6
  "@types/jsonpath": ^0.2.4
  "@types/node": ^22
  "@types/react": ^18.2.37
  "@types/react-dom": ^18.2.15
  "@vitejs/plugin-react": ^4.3.4
  "@web-std/file": ^1.0.4
  asn1js: ^3.0.5
  card-validator: ^8.1.1
  chai: ^4.4.1
  concurrently: ^8.2.2
  crc-32: ^1.2.2
  credit-card-type: ^9.1.0
  deepmerge: ^4.3.1
  del-cli: ^5.0.0
  dotenv: ^16.4.5
  dotenv-cli: ^7.4.1
  eslint: ^9.12.0
  eslint-plugin-react: ^7.37.1
  eslint-plugin-react-hooks: ^5.1.0-rc.0
  events: ^3.3.0
  expo: ~52.0.47
  expo-dev-client: ~5.0.20
  expo-splash-screen: ~0.29.22
  expo-status-bar: ~1.12.1
  express: ^4
  globals: ^15.10.0
  husky: ^9.1.1
  imask: ^7.6.1
  jest: ^28.1.1
  jsdom: ^22.1.0
  jsonpath: ^1.1.1
  jss: ^10.10.0
  jss-preset-default: ^10.10.0
  msw: ^2.7.3
  next: 14.2.25
  nock: ^13.5.4
  node-fetch: ^3
  nodemon: ^3.1.4
  peggy: ^4.0.2
  pino: ^9
  pino-http: ^10
  pod-install: ^0.1.0
  postcss: ^8.4.47
  postcss-load-config: ^4.0.1
  postcss-preset-env: ^8.3.0
  prettier: ^2.8.8
  react: ^18.2.0
  react-dom: ^18.2.0
  react-native: 0.77.3
  react-native-builder-bob: ^0.23.2
  react-native-gesture-handler: ~2.20.2
  react-native-mask-input: ^1.2.3
  react-native-masked-text: ^1.13.0
  react-native-reanimated: ~3.16.1
  react-native-safe-area-context: 4.12.0
  react-native-svg: ^15.6.0
  react-native-web: ~0.19.13
  react-native-webview: ^13.12.5
  rollup-plugin-sri: ^1.3.4
  ts-node: ^10.9.2
  tslib: ^2.7.0
  tsup: ^8.3.5
  typescript: 5.5.4
  typescript-eslint: ^8.8.0
  v8-to-istanbul: ^9.3.0
  vite: ^5.4.11
  vite-plugin-dts: ^4.3.0
  vite-plugin-istanbul: ^6.0.2
  vitest: ^2.1.8
  wait-on: ^8.0.1
