import { EvervaultProvider } from "@evervault/react";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import css from "./styles.module.css";
import plant from "./plant.png";
import Image from "next/image";

const customConfig = {
  jsSdkUrl: process.env.VITE_EVERVAULT_JS_URL as string,
  urls: {
    keysUrl: process.env.VITE_KEYS_URL as string,
    apiUrl: process.env.VITE_API_URL as string,
    componentsUrl: process.env.VITE_UI_COMPONENTS_URL as string,
  },
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <EvervaultProvider
      teamId={process.env.VITE_EV_TEAM_UUID}
      appId={process.env.VITE_EV_APP_UUID}
      customConfig={customConfig}
    >
      <html lang="en">
        <body className={inter.className}>
          <main className={css.main}>
            <div className={css.summary}>
              <div className={css.summaryContent}>
                <h4 className={css.total}>$86.00</h4>
                <Item
                  name="Monstera Deliciosa"
                  description="Large House Plant"
                  price="$50.00"
                  quantity={1}
                />
                <Item
                  name="Monstera Deliciosa"
                  description="Small House Plant"
                  price="$12.00"
                  quantity={2}
                />
                <div className={css.priceRow}>
                  <h6>SubTotal</h6>
                  <strong>$74.00</strong>
                </div>
                <div className={css.priceRow}>
                  <h6>Shipping</h6>
                  <strong>$12.00</strong>
                </div>
                <div className={css.priceRow}>
                  <h6>Total</h6>
                  <strong>$86.00</strong>
                </div>
              </div>
            </div>
            <div className={css.content}>
              <div className={css.container}>{children}</div>
            </div>
          </main>
        </body>
      </html>
    </EvervaultProvider>
  );
}

function Item({ name, description, price, quantity }) {
  return (
    <div className={css.item}>
      <Image
        className={css.image}
        src={plant}
        alt="plant"
        width={60}
        height={60}
      />
      <span className={css.itemName}>{name}</span>
      <span className={css.itemDescription}>{description}</span>
      <span className={css.itemPrice}>{price}</span>
      <span className={css.itemQuantity}>x {quantity}</span>
    </div>
  );
}
