import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { EvervaultProvider } from "@evervault/react";

const customConfig = {
  jsSdkUrl: process.env.VITE_EVERVAULT_JS_URL as string,
  urls: {
    keysUrl: process.env.VITE_KEYS_URL as string,
    apiUrl: process.env.VITE_API_URL as string,
    componentsUrl: process.env.VITE_UI_COMPONENTS_URL as string,
  },
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <EvervaultProvider
      teamId={process.env.VITE_EV_TEAM_UUID}
      appId={process.env.VITE_EV_APP_UUID}
      customConfig={customConfig}
    >
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </EvervaultProvider>
  );
}
