# Deploy package to production envrionment on release
# The tag names created by `changeset tag` include the name of the package we want to release
name: Release Workflow
on:
  workflow_call:
    inputs:
      release-tag:
        description: "The tag name of the release"
        required: true
        type: string
jobs:
  get-package-name-from-tag:
    runs-on: ubuntu-latest
    outputs:
      package-name: ${{ steps.get-package-name.outputs.result }}
    steps:
      - uses: actions/github-script@v7
        id: get-package-name
        env:
          RELEASE_TAG: ${{ inputs.release-tag }}
        with:
          result-encoding: string
          script: |
            const tag = process.env.RELEASE_TAG;
            const semverPrefix = tag.lastIndexOf('@');
            return tag.slice(0,semverPrefix);
  build:
    needs: get-package-name-from-tag
    uses: ./.github/workflows/actions/build.yml
    with:
      vite-evervault-js-url: "https://js.evervault.com/v2"
      vite-keys-url: "https://keys.evervault.com"
      vite-api-url: "https://api.evervault.com"
      environment: "production"
      package-name: ${{ needs.get-package-name-from-tag.outputs.package-name }}
      upload-artifact: true
    secrets: inherit
  deploy-browser:
    if: startsWith(inputs.release-tag, '@evervault/browser')
    needs: build
    uses: ./.github/workflows/actions/deploy-browser.yml
    with:
      environment: "production"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  deploy-inputs:
    if: startsWith(inputs.release-tag, '@evervault/inputs')
    needs: build
    uses: ./.github/workflows/actions/deploy-inputs.yml
    with:
      environment: "production"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  deploy-ui-components:
    if: startsWith(inputs.release-tag, '@evervault/ui-components')
    needs: build
    uses: ./.github/workflows/actions/deploy-ui-components.yml
    with:
      environment: "production"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  deploy-3ds:
    if: startsWith(inputs.release-tag, '@evervault/3ds')
    needs: build
    uses: ./.github/workflows/actions/deploy-3ds.yml
    with:
      environment: "production"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  publish-react:
    if: startsWith(inputs.release-tag, '@evervault/react')
    needs: build
    uses: ./.github/workflows/actions/npm-publish.yml
    with:
      package: "@evervault/react"
      artifact: "react-sdk-build"
      repo_path: "packages/react/dist"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  publish-card-validator:
    if: startsWith(inputs.release-tag, '@evervault/card-validator')
    needs: build
    uses: ./.github/workflows/actions/npm-publish.yml
    with:
      package: "@evervault/card-validator"
      artifact: "card-validator-build"
      repo_path: "packages/card-validator/dist"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  publish-react-native-v2:
    if: startsWith(inputs.release-tag, '@evervault/react-native')
    needs: build
    uses: ./.github/workflows/actions/npm-publish.yml
    with:
      package: "@evervault/react-native"
      artifact: "react-native-build"
      repo_path: "packages/react-native-v2"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  publish-react-native-v1:
    if: startsWith(inputs.release-tag, '@evervault/evervault-react-native')
    needs: build
    uses: ./.github/workflows/actions/npm-publish.yml
    with:
      package: "@evervault/evervault-react-native"
      artifact: "react-native-v1-build"
      repo_path: "packages/react-native"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  publish-eql:
    if: startsWith(inputs.release-tag, '@evervault/eql')
    needs: build
    uses: ./.github/workflows/actions/npm-publish.yml
    with:
      package: "@evervault/eql"
      artifact: "eql-build"
      repo_path: "packages/eql/dist"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  publish-js:
    if: startsWith(inputs.release-tag, '@evervault/js')
    needs: build
    uses: ./.github/workflows/actions/npm-publish.yml
    with:
      package: "@evervault/js"
      artifact: "evervault-js"
      repo_path: "packages/js/dist"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
