name: Publish to npm
on:
  workflow_call:
    inputs:
      package:
        description: "Name of the job"
        required: true
        type: string
      repo_path:
        description: "Where it is in the repo"
        required: true
        type: string
      artifact:
        description: "The artifact containing the built code"
        required: true
        type: string
    secrets:
      PUBLIC_REPO_NPM_PUBLISH:
        description: "NPM Token"
        required: true
jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.repo_path }}
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
      - name: PNPM install
        run: pnpm install --frozen-lockfile
      - name: Publish to npm
        run: pnpm --filter ${{ inputs.package }} publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLIC_REPO_NPM_PUBLISH }}
          NPM_CONFIG_PROVENANCE: true
