# Build and Test packages on pull requests
name: Pull Request Workflow
on:
  pull_request:
    branches:
      - "master"
      - "main"
jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      vite-evervault-js-url: "https://js.evervault.io/v2"
      vite-keys-url: "https://keys.evervault.io"
      vite-api-url: "https://api.evervault.io"
      environment: "staging"
    secrets: inherit
