---
# Build and Test packages on pull requests
name: Pull Request Workflow
on:
  pull_request:
    branches:
      - "master"
      - "main"
jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      vite-evervault-js-url: "https://js.evervault.io/v2"
      vite-keys-url: "https://keys.evervault.io"
      vite-api-url: "https://api.evervault.io"
    secrets:
      TESTS_TEAM_UUID: ${{ secrets.TESTS_TEAM_UUID }}
      TESTS_APP_UUID: ${{ secrets.TESTS_APP_UUID }}
      TESTS_DECRYPT_FN_KEY: ${{ secrets.TESTS_DECRYPT_FN_KEY }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
