# Deploy package to production envrionment on release
# The tag names created by `changeset tag` include the name of the package we want to release
name: Release Workflow
on:
  workflow_call:
    inputs:
      release-tag:
        description: "The tag name of the release"
        required: true
        type: string
jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      vite-evervault-js-url: "https://js.evervault.com/v2"
      vite-keys-url: "https://keys.evervault.com"
      vite-api-url: "https://api.evervault.com"
    secrets: inherit
  deploy-browser:
    if: startsWith(inputs.release-tag, '@evervault/browser')
    needs: build
    uses: ./.github/workflows/deploy-browser.yml
    with:
      environment: "production"
    secrets: inherit
  deploy-inputs:
    if: startsWith(inputs.release-tag, '@evervault/inputs')
    needs: build
    uses: ./.github/workflows/deploy-inputs.yml
    with:
      environment: "production"
    secrets: inherit
  deploy-ui-components:
    if: startsWith(inputs.release-tag, '@evervault/ui-components')
    needs: build
    uses: ./.github/workflows/deploy-ui-components.yml
    with:
      environment: "production"
    secrets: inherit
  deploy-3ds:
    if: startsWith(inputs.release-tag, '@evervault/3ds')
    needs: build
    uses: ./.github/workflows/deploy-3ds.yml
    with:
      environment: "production"
    secrets: inherit
  publish-react:
    if: startsWith(inputs.release-tag, '@evervault/react')
    needs: build
    uses: ./.github/workflows/npm-publish.yml
    with:
      package: "@evervault/react"
      artifact: "react-sdk-build"
      repo_path: "packages/react/dist"
    secrets: inherit
  publish-card-validator:
    if: startsWith(inputs.release-tag, '@evervault/card-validator')
    needs: build
    uses: ./.github/workflows/npm-publish.yml
    with:
      package: "@evervault/card-validator"
      artifact: "card-validator-build"
      repo_path: "packages/card-validator/dist"
    secrets: inherit
  publish-react-native-v2:
    if: startsWith(inputs.release-tag, '@evervault/react-native')
    needs: build
    uses: ./.github/workflows/npm-publish.yml
    with:
      package: "@evervault/react-native"
      artifact: "react-native-build"
      repo_path: "packages/react-native-v2"
    secrets: inherit
  publish-react-native-v1:
    if: startsWith(inputs.release-tag, '@evervault/evervault-react-native')
    needs: build
    uses: ./.github/workflows/npm-publish.yml
    with:
      package: "@evervault/evervault-react-native"
      artifact: "react-native-v1-build"
      repo_path: "packages/react-native"
    secrets: inherit
  publish-eql:
    if: startsWith(inputs.release-tag, '@evervault/eql')
    needs: build
    uses: ./.github/workflows/npm-publish.yml
    with:
      package: "@evervault/eql"
      artifact: "eql-build"
      repo_path: "packages/eql/dist"
    secrets: inherit
  publish-js:
    if: startsWith(inputs.release-tag, '@evervault/js')
    needs: build
    uses: ./.github/workflows/npm-publish.yml
    with:
      package: "@evervault/js"
      artifact: "evervault-js"
      repo_path: "packages/js/dist"
    secrets: inherit
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get package name
        env:
          TAG: ${{ inputs.release-tag }}
        id: parse
        run: |
          if [[ "$TAG" == *"evervault-react-native"* ]]; then
            echo "name=react-native" >> $GITHUB_OUTPUT
          else
            name_part=${TAG##*/}
            echo "name=${name_part%@*}" >> $GITHUB_OUTPUT
          fi
      - uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}/packages/${{ steps.parse.outputs.name }}/CHANGELOG.md
