# Deploy package to production envrionment on release
# The tag names created by `changeset tag` include the name of the package we want to release
name: Release Workflow
on:
  workflow_call:
    inputs:
      release-tag:
        description: "The tag name of the release"
        required: true
        type: string
jobs:
  get-package-name-from-tag:
    runs-on: ubuntu-latest
    outputs:
      package-name: ${{ steps.get-package-name.outputs.result }}
    steps:
      - uses: actions/github-script@v7
        id: get-package-name
        env:
          RELEASE_TAG: ${{ inputs.release-tag }}
        with:
          result-encoding: string
          script: |
            const tag = process.env.RELEASE_TAG;
            const semverPrefix = tag.lastIndexOf('@');
            return tag.slice(0,semverPrefix);
  build:
    needs: get-package-name-from-tag
    uses: ./.github/workflows/build.yml
    with:
      vite-evervault-js-url: "https://js.evervault.com/v2"
      vite-keys-url: "https://keys.evervault.com"
      vite-api-url: "https://api.evervault.com"
      environment: "production"
      package-name: ${{ needs.get-package-name-from-tag.outputs.package-name }}
      upload-artifact: true
    secrets: inherit
  deploy-browser:
    needs: [build]
    if: startsWith(inputs.release-tag, '@evervault/browser')
    uses: ./.github/workflows/publish-static-bundle.yml
    with:
      package-name: '@evervault/browser'
      stage: "production"
      environment: 'browser-production'
      run-preflight-checks: true
      perform-gated-preview-deployment: true
      cloudfront-preview-path-invalidation: "/v2/preview/index.js"
      cloudfront-live-path-invalidation: "/v2/index.js"
      asset-subdomain: "js"
      s3-bucket-var-name: 'BROWSER_SDK_S3_BUCKET'
      cloudfront-distribution-id: 'BROWSER_SDK_CLOUDFRONT_DISTRIBUTION_ID'
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  deploy-inputs:
    needs: [build]
    if: startsWith(inputs.release-tag, '@evervault/inputs')
    uses: ./.github/workflows/publish-static-bundle.yml
    with:
      package-name: '@evervault/inputs'
      environment: 'production'
      run-preflight-checks: false
      perform-gated-preview-deployment: false
      cloudfront-live-path-invalidation: "/index.html,/bundle.js,/v2/*"
      s3-bucket-var-name: 'INPUTS_S3_BUCKET'
      cloudfront-distribution-id: 'INPUTS_CLOUDFRONT_DISTRIBUTION_ID'
      stage: "production"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  deploy-ui-components:
    needs: [build]
    if: startsWith(inputs.release-tag, '@evervault/ui-components')
    uses: ./.github/workflows/publish-static-bundle.yml
    with:
      package-name: '@evervault/ui-components'
      stage: "production"
      environment: 'ui-components-production'
      run-preflight-checks: true
      perform-gated-preview-deployment: true
      s3-bucket-var-name: 'UI_COMPONENTS_S3_BUCKET'
      cloudfront-preview-path-invalidation: "/preview/index.html"
      cloudfront-live-path-invalidation: "/index.html,/assets/*"
      asset-subdomain: "ui-components"
      cloudfront-distribution-id: 'UI_COMPONENTS_CLOUDFRONT_DISTRIBUTION_ID'
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  deploy-3ds:
    needs: [build]
    if: startsWith(inputs.release-tag, '@evervault/3ds')
    uses: ./.github/workflows/publish-static-bundle.yml
    with:
      package-name: '@evervault/3ds'
      stage: "production"
      environment: 'production'
      run-preflight-checks: false
      perform-gated-preview-deployment: false
      s3-bucket-var-name: 'TDS_AWS_S3_BUCKET'
      cloudfront-live-path-invalidation: "/index.html"
      cloudfront-distribution-id: 'TDS_AWS_CLOUDFRONT_DISTRIBUTION_ID'
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  publish-react:
    if: startsWith(inputs.release-tag, '@evervault/react')
    needs: build
    uses: ./.github/workflows/npm-publish.yml
    with:
      package: "@evervault/react"
      artifact: "react-sdk-build"
      repo_path: "packages/react/dist"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  publish-card-validator:
    if: startsWith(inputs.release-tag, '@evervault/card-validator')
    needs: build
    uses: ./.github/workflows/npm-publish.yml
    with:
      package: "@evervault/card-validator"
      artifact: "card-validator-build"
      repo_path: "packages/card-validator/dist"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  publish-react-native-v2:
    if: startsWith(inputs.release-tag, '@evervault/react-native')
    needs: build
    uses: ./.github/workflows/npm-publish.yml
    with:
      package: "@evervault/react-native"
      artifact: "react-native-build"
      repo_path: "packages/react-native-v2"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  publish-react-native-v1:
    if: startsWith(inputs.release-tag, '@evervault/evervault-react-native')
    needs: build
    uses: ./.github/workflows/npm-publish.yml
    with:
      package: "@evervault/evervault-react-native"
      artifact: "react-native-v1-build"
      repo_path: "packages/react-native"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  publish-eql:
    if: startsWith(inputs.release-tag, '@evervault/eql')
    needs: build
    uses: ./.github/workflows/npm-publish.yml
    with:
      package: "@evervault/eql"
      artifact: "eql-build"
      repo_path: "packages/eql/dist"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
  publish-js:
    if: startsWith(inputs.release-tag, '@evervault/js')
    needs: build
    uses: ./.github/workflows/npm-publish.yml
    with:
      package: "@evervault/js"
      artifact: "evervault-js"
      repo_path: "packages/js/dist"
      tag_name: ${{ inputs.release-tag }}
    secrets: inherit
